[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[sidebar]
showSidebarNavigation = true
# Kita biarkan auto agar user bisa buka/tutup dengan normal
state = "auto"
